<?php

$lower_saxony_array = array(
	
	'0'         => 'Gifhorn',
	'1'			=> 'Celle',
	'2'			=> 'Lüchow-Dannenberg',
	'3'			=> 'Uelzen',
	'4'			=> 'Lüneburg',
	'5'			=> 'Heidekreis',
	'6'			=> 'Harburg',
	'7'			=> 'Stade',
	'8'			=> 'Rotenburg (Wümme)',
	'9'			=> 'Verden',
	'10'		=> 'Osterholz',
	'11'		=> 'Cuxhaven',
	'12'		=> 'Osnabrück (Stadt)',
	'13'		=> 'Osnabrück (Landkreis)',
	'14'		=> 'Vechta',
	'15'		=> 'Diepholz',
	'16'		=> 'Delmenhorst',
	'17'		=> 'Oldenburg',
	'18'		=> 'Oldenburg (Stadt/Oldenburg)',
	'19'		=> 'Wesermarsch',
	'20'		=> 'Grafschaft Bentheim',
	'21'		=> 'Emsland',
	'22'		=> 'Cloppenburg',
	'23'		=> 'Ammerland',
	'24'		=> 'Wilhelmshaven',
	'25'		=> 'Emden',
	'26'		=> 'Leer',
	'27'		=> 'Holzminden',
	'28'		=> 'Hameln-Pyrmont',
	'29'		=> 'Hildesheim',
	'30'		=> 'Wolfsburg',
	'31'		=> 'Helmstedt',
	'32'		=> 'Braunschweig',
	'33'		=> 'Peine',
	'34'		=> 'Schaumburg',
	'35'		=> 'Region Hannover',
	'36'		=> 'Nienburg (Weser)',
	'37'		=> 'Göttingen',
	'38'		=> 'Osterode am Harz',
	'39'		=> 'Goslar',
	'40'		=> 'Northeim',
	'41'		=> 'Wolfenbüttel',
	'42'		=> 'Salzgitter',
	'43'		=> 'Friesland',
	'44'		=> 'Wittmund',
	'45'		=> 'Aurich',
	'46'		=> 'Bremen',
	
);

?>